# Generated by Django 4.1.7 on 2023-07-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_scheduler_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='Username',
            field=models.CharField(default='yifenghuang@hotmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_19_17_05_25', max_length=200),
        ),
    ]
