# Generated by Django 4.1.7 on 2023-07-19 17:34

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_scheduler_username_alter_scheduler_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='Date',
            field=models.DateField(default=scheduler.models.Scheduler.one_week_ahead),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_19_17_34_54', max_length=200),
        ),
    ]
