# Generated by Django 4.1.7 on 2023-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_scheduler_date_alter_scheduler_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='Time_Slot_first_pick',
            new_name='Time_Slot',
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_19_18_05_47', max_length=200),
        ),
    ]
