# Generated by Django 4.1.7 on 2023-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_rename_time_slot_first_pick_scheduler_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='Player',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=4),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_19_18_11_23', max_length=200),
        ),
    ]
