# Generated by Django 4.1.7 on 2023-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_scheduler_player_alter_scheduler_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='Website_Url',
            field=models.CharField(default='https://foreupsoftware.com/booking/20954#/login', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_19_18_25_30', max_length=200),
        ),
    ]
