# Generated by Django 4.1.7 on 2023-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_scheduler_website_url_alter_scheduler_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_19_18_47_20', max_length=200),
        ),
    ]
