# Generated by Django 4.2.1 on 2023-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_remove_scheduler_player_alter_scheduler_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='Email',
            field=models.CharField(default='zhen.gong@predictifsolutions.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_28_17_00_25', max_length=200),
        ),
    ]
