# Generated by Django 4.2.1 on 2023-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_scheduler_email_alter_scheduler_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_28_17_02_49', max_length=200),
        ),
    ]
