# Generated by Django 4.2.1 on 2023-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_alter_scheduler_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='Schedule_Hour',
            new_name='Job_1_Schedule_Hour',
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='Schedule_Minute',
            new_name='Job_1_Schedule_Minute',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='Schedule_Day',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='Job_1_Schedule_Day',
            field=models.CharField(default='sun', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='Job_2_Schedule_Day',
            field=models.CharField(default='sun', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='Job_2_Schedule_Hour',
            field=models.CharField(default='2', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='Job_2_Schedule_Minute',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='Job_2_Start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='title',
            field=models.CharField(default='task-2023_07_28_17_39_45', max_length=200),
        ),
    ]
